name = "MainPaths"
uuid = "f429ff72-55f4-4340-8292-212120acb409"
authors = ["Jakob Hoffmann <jfb-hoffmann@hotmail.de> and contributors"]
version = "0.1.0"

[deps]
LightGraphs = "093fc24a-ae57-5d10-9952-331d41423f4d"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
